import SideBar from "@/components/Shared/SideBar";

export const metadata = {
  title: "Next.js Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
  return (
    <div className="flex">
      <SideBar />
      <div className="w-full">{children}</div>
    </div>
  );
};

export default DashboardLayout;
